spring.secondDatasource.url=jdbc:sqlserver://localhost:1111
spring.secondDatasource.username=sa
spring.secondDatasource.password=1111


spring.datasource.url=jdbc:sqlserver://localhost:111
spring.datasource.username=sa
spring.datasource.password=1111
